trigger:
  branches:
    include: ["*"]
  tags:
    include: ["*"]

# https://github.com/xoac/rust-azure-pipelines
resources:
  repositories:
    - repository: rust_pipelines
      type: github
      name: ctaggart/rust-azure-pipelines
      endpoint: github.com_ctaggart

# stages:
#   - stage: check
#     displayName: "Build"
#     jobs:
#       - job: Linux

pool:
  vmImage: "ubuntu-20.04"
steps:
  - script: echo "A"
  - template: ci/steps/install-rust.yml@rust_pipelines
  - script: cargo build --release
  - script: cargo run -- a b c
  - script: $(Agent.BuildDirectory)/target/release/vstest d e f
