trigger:
  branches:
    include: ['*']
  tags:
    include: ['*']

# https://github.com/xoac/rust-azure-pipelines
resources:
  repositories:
    - repository: rust_pipelines
      type: github
      name: ctaggart/rust-azure-pipelines
      endpoint: github.com_ctaggart

stages:
- stage: check
  displayName: "Quick checks"
  jobs:
  - template: ci/scenarios/check.yml@rust_pipelines