trigger:
  branches:
    include: ["*"]
  tags:
    include: ["*"]

# https://github.com/xoac/rust-azure-pipelines
resources:
  repositories:
    - repository: rust_pipelines
      type: github
      name: ctaggart/rust-azure-pipelines
      endpoint: github.com_ctaggart

pool:
  vmImage: "ubuntu-20.04"
steps:
  - script: echo "A"
  - template: ci/steps/install-rust.yml@rust_pipelines
  - script: cargo build --release
  # - script: cargo run -- a b c
  # - script: $(Build.Repository.LocalPath)/target/release/vstest d e f
  - task: VSTest@2
    inputs:
      vstestLocation: $(Build.Repository.LocalPath)/target/release/vstest
